version: '3.9'

services:
  app:
    image: golang:latest
    container_name: go_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=54354
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "54354:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: